server:
  port: 9898

spring:
  datasource:
    primary:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost;DataBaseName=analysis_szqc_nb_new
      username: sa
      password: 123456

    second:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      jdbc-url: jdbc:sqlserver://localhost;DataBaseName=zcjy_by
      username: sa
      password: 123456
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#客户端地址
app:
  server:
    host:
      url: http://192.168.0.16:8081/stats_api
  login:
    url: /login
  logout:
    url: /logout

  #前端首页地址
  home:
    url: http://192.168.0.16:8081/dist/#/msxz

#cas认证中心地址
cas:
  server:
    host: http://192.168.0.16:8080/cas
    login_url: http://192.168.0.16:8080/cas/login
    logout_url: http://192.168.0.16:8080/cas/logout?service=http://192.168.0.16:8081/stats_api/login
#cas:
#  server:
#    host: http://192.168.0.101:8024/cas
#    login_url: http://192.168.0.101:8024/cas/login
#    logout_url: http://192.168.0.101:8024/cas/logout?service=http://localhost:9898/apis/login

stats:
  asset-database: analysis_szqc2021

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace