server:
  port: 9898
#  servlet:
#    context-path: /stats
spring:
  profiles:
    active: dm


rocketmq:
  name-server: 192.168.0.16:9876
#  name-server: 192.168.0.101:9876
  producer:
    group: my-group

